model:
  fc_dim: 256
  N_layer: 3
  n_head: 1

train:
  epochs: 200
  coor_sampling_size: 500
  batchsize: 200 
  coor_sampling_freq: 3
  base_lr: 0.0001
  visual_freq: 20
  weight_bc: 1000
  weight_pde: 1