model:
  fc_dim: 256
  N_layer: 3
  n_head: 1

train:
  epochs: 2000
  coor_sampling_size: 300
  batchsize: 10
  coor_sampling_freq: 3
  base_lr: 0.0001
  visual_freq: 10
  weight_load: 1
  weight_pde: 1
  weight_fix: 1
  weight_free: 1